"""empty message

Revision ID: d62b3b7ba046
Revises: e4c8e20a10d3
Create Date: 2016-07-13 14:22:13.454474

"""

# revision identifiers, used by Alembic.
revision = 'd62b3b7ba046'
down_revision = 'e4c8e20a10d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    ### end Alembic commands ###
